apiVersion: v1
data:
  application.html: |
    {{ .Values.application.content }}
    <body>
    <img src="https://robohash.org/{{ toJson .Values | sha256sum }}.png">
    </body>
kind: ConfigMap
metadata:
  name: application-prod
  namespace: {{ .Values.namespace }}
